name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install WebView2 NuGet
        run: dotnet add src/LockedBrowser-GitHubTemplate/LockedBrowser.csproj package Microsoft.Web.WebView2

      - name: Build project
        run: |
          dotnet publish src/LockedBrowser-GitHubTemplate/LockedBrowser.csproj -c Release -r win-x64 --self-contained false -o artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LockedBrowser
          path: artifacts/
